ci:
  skip: [cppcheck, clang-tidy]
fail_fast: false

repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=200]
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-vcs-permalinks
  - id: check-xml
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: double-quote-string-fixer
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]

- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
  - id: check-mailmap
  - id: git-check

- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 2.4.0
  hooks:
  - id: editorconfig-checker

- repo: https://github.com/commitizen-tools/commitizen
  rev: v2.23.0
  hooks:
  - id: commitizen
    stages: [commit-msg]

- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell

- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.31.1
  hooks:
  - id: markdownlint
    args: [--config=.markdownlint.yml, scan]

- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.1.13
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
    args: [--whitespaces-count, '2']

- repo: https://github.com/Kr4is/cmake-format-precommit
  rev: v0.6.14
  hooks:
  - id: cmake-format
    args: [--config=.cmake-format.yml]
  - id: cmake-lint
    args: [--config=.cmake-linter.yml]

- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
  - id: pretty-format-toml
  - id: pretty-format-ini

- repo: https://github.com/sirosen/check-jsonschema
  rev: 0.14.2
  hooks:
  - id: check-github-actions
  - id: check-github-workflows

- repo: https://github.com/Takishima/cmake-pre-commit-hooks
  rev: v1.5.2
  hooks:
  - id: clang-tidy
    args: [-Bbuild, -S., -DCMMM_TIMEOUT=30, -DCMMM_INACTIVITY_TIMEOUT=30]
  - id: cppcheck
    args: [-Bbuild, -S., -DCMMM_TIMEOUT=30, -DCMMM_INACTIVITY_TIMEOUT=30, --max-ctu-depth=50, --enable=all, --project=compile_commands.json, --inline-suppr, -ibuild/_deps/*, --suppressions-list=.cppcheck, --cppcheck-build-dir=build, -j20]

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v13.0.1
  hooks:
  - id: clang-format

- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0
  hooks:
  - id: cpplint
