/*
* Khaos
* C/C++ library for writing cross-platform codes.
*
* SPDX-FileCopyrightText: 2020-2024 flagarde
*
* SPDX-License-Identifier: MIT
*/

/* Copyright 2022 flagarde */

#include "Khaos/CompareVersions.h"
#include "Khaos/KhaosVersion.h"

// NOLINTBEGIN
#if defined(_WIN32) && !defined(__MINGW32__) && !defined(__MINGW64__)
  #pragma warning(disable : 4805)
#endif
#include "doctest/doctest.h"
// NOLINTEND

TEST_CASE("Test CHECK_VERSION(x,>,major,minor,patch)")
{
  CHECK_EQ(0, CHECK_VERSION(Khaos, >, MAJOR, MINOR, PATCH, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, >, MAJOR, MINOR, PATCH + 1, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, >, MAJOR, MINOR + 1, PATCH, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, >, MAJOR + 1, MINOR, PATCH, TWEAK));
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, >, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH + 1, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, >, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR + 1, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, >, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR + 1, MINOR, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, >, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
}

TEST_CASE("Test CHECK_VERSION(x,>=,major,minor,patch)")
{
  CHECK_EQ(1, CHECK_VERSION(Khaos, >=, MAJOR, MINOR, PATCH, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, >=, MAJOR, MINOR, PATCH + 1, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, >=, MAJOR, MINOR + 1, PATCH, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, >=, MAJOR + 1, MINOR, PATCH, TWEAK));
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, >=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH + 1, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, >=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR + 1, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, >=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR + 1, MINOR, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, >=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
}

TEST_CASE("Test CHECK_VERSION(x,==,major,minor,patch)")
{
  CHECK_EQ(1, CHECK_VERSION(Khaos, ==, MAJOR, MINOR, PATCH, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, ==, MAJOR, MINOR, PATCH + 1, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, ==, MAJOR, MINOR + 1, PATCH, TWEAK));
  CHECK_EQ(0, CHECK_VERSION(Khaos, ==, MAJOR + 1, MINOR, PATCH, TWEAK));
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, ==, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH + 1, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, ==, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR + 1, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, ==, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR + 1, MINOR, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, ==, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
}

TEST_CASE("Test CHECK_VERSION(x,<=,major,minor,patch)")
{
  CHECK_EQ(1, CHECK_VERSION(Khaos, <=, MAJOR, MINOR, PATCH, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, <=, MAJOR, MINOR, PATCH + 1, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, <=, MAJOR, MINOR + 1, PATCH, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, <=, MAJOR + 1, MINOR, PATCH, TWEAK));
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, <=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH + 1, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, <=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR + 1, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, <=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR + 1, MINOR, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, <=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
}

TEST_CASE("Test CHECK_VERSION(x,<,major,minor,patch)")
{
  CHECK_EQ(0, CHECK_VERSION(Khaos, <, MAJOR, MINOR, PATCH, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, <, MAJOR, MINOR, PATCH + 1, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, <, MAJOR, MINOR + 1, PATCH, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, <, MAJOR + 1, MINOR, PATCH, TWEAK));
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, <, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH + 1, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, <, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR + 1, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, <, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR + 1, MINOR, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, <, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
}

TEST_CASE("Test CHECK_VERSION(x,!=,major,minor,patch)")
{
  CHECK_EQ(0, CHECK_VERSION(Khaos, !=, MAJOR, MINOR, PATCH, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, !=, MAJOR, MINOR, PATCH + 1, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, !=, MAJOR, MINOR + 1, PATCH, TWEAK));
  CHECK_EQ(1, CHECK_VERSION(Khaos, !=, MAJOR + 1, MINOR, PATCH, TWEAK));
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH, TWEAK)
  CHECK_EQ(0, CHECK_VERSION(Test, !=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH + 1, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, !=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR + 1, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, !=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
#define KHAOS_DEFINE_Test_VERSION_PRIVATE() SET_VERSION(MAJOR + 1, MINOR, PATCH, TWEAK)
  CHECK_EQ(1, CHECK_VERSION(Test, !=, GET_VERSION_MAJOR(Khaos), GET_VERSION_MINOR(Khaos), GET_VERSION_PATCH(Khaos), GET_VERSION_TWEAK(Khaos)));
#undef KHAOS_DEFINE_Test_VERSION_PRIVATE
}

/* Test CHECK_VERSIONS */
#define KHAOS_DEFINE_Test1_VERSION_PRIVATE() SET_VERSION(MAJOR, MINOR, PATCH, TWEAK)
#define KHAOS_DEFINE_Test2_VERSION_PRIVATE() SET_VERSION(MAJOR + 1, MINOR, PATCH, TWEAK)
TEST_CASE("Test CHECK_VERSIONS(x,>,y)") { CHECK_EQ(0, CHECK_VERSIONS(Test1, >, Test2)); }

TEST_CASE("Test CHECK_VERSIONS(x,>=,y)") { CHECK_EQ(0, CHECK_VERSIONS(Test1, >=, Test2)); }

TEST_CASE("Test CHECK_VERSIONS(x,==,y)") { CHECK_EQ(0, CHECK_VERSIONS(Test1, ==, Test2)); }

TEST_CASE("Test CHECK_VERSIONS(x,<=,y)") { CHECK_EQ(1, CHECK_VERSIONS(Test1, <=, Test2)); }

TEST_CASE("Test CHECK_VERSIONS(x,<,y)") { CHECK_EQ(1, CHECK_VERSIONS(Test1, <, Test2)); }

TEST_CASE("Test CHECK_VERSIONS(x,!=,y)") { CHECK_EQ(1, CHECK_VERSIONS(Test1, !=, Test2)); }
#undef KHAOS_DEFINE_Test1_VERSION_PRIVATE
#undef KHAOS_DEFINE_Test2_VERSION_PRIVATE
