// Copyright 2022 flagarde

#include "khaos/VersionMacros.h"

#include <doctest/doctest.h>

#define KHAOS_VERSION_Test_PRIVATE()       SET_VERSION(2, 3, 4)
#define KHAOS_VERSION_Test_TWEAK_PRIVATE() SET_VERSION_TWEAK(5)

TEST_CASE("Test GET_VERSION_MAJOR(x)")
{
  CHECK_EQ(MAJOR, GET_VERSION_MAJOR(Khaos));
  CHECK_EQ(2, GET_VERSION_MAJOR(Test));
}

TEST_CASE("Test GET_VERSION_MINOR(x)")
{
  CHECK_EQ(MINOR, GET_VERSION_MINOR(Khaos));
  CHECK_EQ(3, GET_VERSION_MINOR(Test));
}

TEST_CASE("Test GET_VERSION_PATCH(x)")
{
  CHECK_EQ(PATCH, GET_VERSION_PATCH(Khaos));
  CHECK_EQ(4, GET_VERSION_PATCH(Test));
}

TEST_CASE("Test GET_VERSION_TWEAK(x)")
{
  CHECK_EQ(TWEAK, GET_VERSION_TWEAK(Khaos));
  CHECK_EQ(5, GET_VERSION_TWEAK(Test));
}

#undef KHAOS_VERSION_Test_PRIVATE
#undef KHAOS_VERSION_Test_TWEAK_PRIVATE
