---
name: Dockcross

on:
  push:
    branches:
    - '*'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - '*'

jobs:
  android:
    name: Build ${{ matrix.image_name }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Remove images that you do not need
        image_name: [android-arm, android-arm64, android-x86, android-x86_64]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Make script dockcross-${{ matrix.image_name }}
      run: docker run --rm dockcross/${{ matrix.image_name }} > ./dockcross-${{ matrix.image_name }}; chmod +x ./dockcross-${{ matrix.image_name }}

    - name: Run CMake
      run: ./dockcross-${{ matrix.image_name }} cmake -B build -S . -G Ninja

    - name: Compile
      run: ./dockcross-${{ matrix.image_name }} ninja -C build

  linux:
    name: Build ${{ matrix.image_name }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Remove images that you do not need
        image_name: [linux-arm64, linux-arm64-musl, linux-armv5, linux-armv5-musl, linux-armv5-uclibc, linux-armv6, linux-armv6-musl, linux-armv7, linux-armv7a, linux-armv7l-musl, linux-mips, linux-mipsel-lts, linux-s390x, linux-ppc64le, linux-riscv32,
          linux-riscv64, linux-m68k-uclibc, linux-xtensa-uclibc, linux-x86, linux-x64, linux-x64-clang, linux-x64-tinycc]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Make script dockcross-${{ matrix.image_name }}
      run: docker run --rm dockcross/${{ matrix.image_name }} > ./dockcross-${{ matrix.image_name }}; chmod +x ./dockcross-${{ matrix.image_name }}

    - name: Run CMake
      run: ./dockcross-${{ matrix.image_name }} cmake -B build -S . -G Ninja

    - name: Compile
      run: ./dockcross-${{ matrix.image_name }} ninja -C build

  windows:
    name: Build ${{ matrix.image_name }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Remove images that you do not need
        image_name: [windows-shared-x86, windows-shared-x64, windows-shared-x64-posix, windows-static-x86, windows-static-x64, windows-static-x64-posix, windows-armv7, windows-arm64]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Make script dockcross-${{ matrix.image_name }}
      run: docker run --rm dockcross/${{ matrix.image_name }} > ./dockcross-${{ matrix.image_name }}; chmod +x ./dockcross-${{ matrix.image_name }}

    - name: Run CMake
      run: ./dockcross-${{ matrix.image_name }} cmake -B build -S . -G Ninja

    - name: Compile
      run: ./dockcross-${{ matrix.image_name }} ninja -C build

  web:
    name: Build ${{ matrix.image_name }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Remove images that you do not need
        image_name: [web-wasm, web-wasi]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Make script dockcross-${{ matrix.image_name }}
      run: docker run --rm dockcross/${{ matrix.image_name }} > ./dockcross-${{ matrix.image_name }}; chmod +x ./dockcross-${{ matrix.image_name }}

    - name: Run CMake
      run: ./dockcross-${{ matrix.image_name }} cmake -B build -S . -G Ninja

    - name: Compile
      run: ./dockcross-${{ matrix.image_name }} ninja -C build
