name: Dockcross

on:
  push:
    branches:
    - '*'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - '*'

jobs:
  image:
    name: Build ${{ matrix.image_name }} ${{ matrix.build_type }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Remove images that you do not need
        image_name:
        - android-arm
        - android-arm64
        - android-x86
        - android-x86_64
        - linux-arm64
        - linux-arm64-lts
        - linux-arm64-full
        - linux-arm64-musl
        - linux-armv5
        - linux-armv5-musl
        - linux-armv5-uclibc
        - linux-armv6
        - linux-armv6-lts
        - linux-armv6-musl
        - linux-armv7
        - linux-armv7-lts
        - linux-armv7a
        - linux-armv7l-musl
        - linux-mips
        - linux-s390x
        - linux-ppc64le
        - linux-riscv64
        - linux-riscv32
        - linux-m68k-uclibc
        - linux-xtensa-uclibc
        - manylinux2014-x64
        - manylinux2014-x86
        - linux-x86
        - linux-x64
        - linux-x86_64-full
        - linux-x64-clang
        - linux-x64-tinycc
        - web-wasm
        - web-wasi
        - windows-shared-x86
        - windows-shared-x64
        - windows-shared-x64-posix
        - windows-static-x86
        - windows-static-x64
        - windows-static-x64-posix
        - windows-armv7
        - windows-arm64
        - manylinux2014-aarch64
        # Disable MinSizeRel RelWithDebInfo Debug Release
        build_type: [Debug]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0
    - name: build
      run: ./.github/workflows/dockcross-cmake-builder.sh ${{ matrix.image_name }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
