name: include-what-you-use

on:
  pull_request:
  push:
    paths-ignore:
    - docs/**
    branches: [main]

jobs:
  include-what-you-use:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Generate compilation database
      run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -S . -B ./build

    - name: Run include-what-you-use
      uses: external-packages/include-what-you-use-action@v2.0
      with:
        compilation-database-path: ./build
        output-format: iwyu     # Or 'clang'
        no-error: 'true'

    - name: Run static analysis
      uses: JacobDomagala/StaticAnalysis@v0.0.4
      with:
        # (Optional) clang-tidy args
        clang_tidy_args: -checks='*,fuchsia-*,google-*,zircon-*,abseil-*,modernize-use-trailing-return-type'
        # (Optional) cppcheck args
        cppcheck_args: --enable=all --suppress=missingInclude
