---
name: pre-commit

on:
  pull_request:
  push:
    paths-ignore:
    - docs/**
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install packages
      run: sudo apt-get install clang-tidy cmake

    - name: 🔧 Configure
      run: cmake -S . -B ./build -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DKHAOS_BUILD_TESTS:BOOL=OFF -DKHAOS_BUILD_DOCS:BOOL=OFF -DKHAOS_BUILD_EXAMPLES:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=./install -DCMAKE_NUMBER_JOBS:STRING=2 -DCMAKE_NUMBER_JOBS_TESTS:STRING=1

    - uses: pre-commit/action@v3.0.1

    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
