---
name: pre-commit

on:
  pull_request:
  push:
    paths-ignore:
    - docs/**
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: sudo apt-get install clang-tidy cmake

    - name: 🔧 Configure
      run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_NUMBER_JOBS=2 -DCMAKE_NUMBER_JOBS_TESTS=1

    - uses: pre-commit/action@v3.0.0
