---
name: pre-commit

on:
  pull_request:
  push:
    paths-ignore:
    - docs/**
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest

    steps:
    - uses: actions/checkout@v3

    - name: Install packages
      run: apk --update-cache add clang-extra-tools cppcheck include-what-you-use cmake g++

    - name: 🔧 Configure
      run: cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DBUILD_DOCS=OFF -DBUILD_EXAMPLES=ON -DCMAKE_INSTALL_PREFIX=./install -DCMAKE_NUMBER_JOBS=2 -DCMAKE_NUMBER_JOBS_TESTS=1

    - uses: pre-commit/action@v2.0.3
